app/api_engine/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    FunctionListView,
    FunctionView,
    FunctionCustomerView,
    FunctionExecutionListView,
    FunctionExecutionView,
    EnvironmentVariableView,
    DomainListView,
    DomainView,
    CustomerView,
    CustomerListView,
)

app_name = "api_engine"

urlpatterns = [
    path(
        "function/list/",
        login_required(FunctionListView.as_view()),
        name="function-list",
    ),
    path("function/", login_required(FunctionView.as_view()), name="function"),
    path(
        "function/<int:function_id>",
        login_required(FunctionView.as_view()),
        name="function",
    ),
    path(
        "function/<int:function_id>/customer",
        login_required(FunctionCustomerView.as_view()),
        name="function-customer",
    ),
    path(
        "function/execution/list",
        login_required(FunctionExecutionListView.as_view()),
        name="function-execution-list",
    ),
    path(
        "function/execution/<int:execution_id>",
        login_required(FunctionExecutionView.as_view()),
        name="function-execution",
    ),
    path(
        "environment-variables/<int:function_id>",
        login_required(EnvironmentVariableView.as_view()),
        name="environment-variable",
    ),
    path("domain/list/", login_required(DomainListView.as_view()), name="domain-list"),
    path("domain/", login_required(DomainView.as_view()), name="domain"),
    path("domain/<int:domain_id>", login_required(DomainView.as_view()), name="domain"),
    path(
        "customer/list/",
        login_required(CustomerListView.as_view()),
        name="customer-list",
    ),
    path("customer/", login_required(CustomerView.as_view()), name="customer"),
    path(
        "customer/<int:customer_id>",
        login_required(CustomerView.as_view()),
        name="customer",
    ),
]

app/core/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from django.contrib.auth.decorators import login_required
from . import views
from .views import LoginView, index, LogoutView, ChangePasswordView


urlpatterns = [
    path("", RedirectView.as_view(url="index", permanent=False)),
    path("index/", login_required(index), name="index"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("change-password/", ChangePasswordView.as_view(), name="change-password"),
]

app/ia_engine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from core import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    #path("", views.index, name="index"),
    #path("", RedirectView.as_view(url="index", permanent=False)),
    #path("core", include("core.urls")),
    path("task_engine/", include("task_engine.urls")),
    path("api/", include("api_engine.urls_functions")),
    path("api_engine/", include("api_engine.urls")),
]

app/api_engine/models.py
from core.models import Team
from contextlib import redirect_stdout

from django.db import models
from django.core import signing
from django.contrib.auth.models import User
from django.urls import reverse
from django.conf import settings

from functools import cached_property

from io import StringIO
from simple_history.models import HistoricalRecords
from typing import Any

from .choices import HTTP_METHOD_CHOICE, HTTP_METHOD_GET
from .constants import FUNCTION_REQUEST_CLASS_NAME, FUNCTION_RESPONSE_CLASS_NAME

import json
import traceback
import sys


class DomainFunctionService(models.Model):
    name = models.CharField(max_length=500)
    url_name = models.CharField(max_length=500)
    created_date = models.DateTimeField(auto_now_add=True)
    last_updated_date = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
        related_name="domain_function_service_created_by",
    )
    last_updated_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
        related_name="domain_function_service_last_updated_by",
    )
    team = models.ForeignKey(Team, on_delete=models.DO_NOTHING)
    active = models.BooleanField(default=True)
    history = HistoricalRecords()

    def __str__(self) -> str:
        return self.name

    def get_html_hyperlink(self) -> str:
        domain_link = reverse("api_engine:domain", args=(self.id,))
        return f"<a href='{domain_link}'>{self.name}</a>"

    class Meta:
        db_table = "domain_function_service"


class FunctionService(models.Model):
    name = models.CharField(max_length=500)
    domain = models.ForeignKey(DomainFunctionService, on_delete=models.CASCADE)
    url_name = models.CharField(max_length=500)
    description = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    last_updated_date = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
        related_name="function_server_created_by",
    )
    last_updated_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
        related_name="function_server_last_updated_by",
    )
    team = models.ForeignKey(Team, on_delete=models.DO_NOTHING)
    http_method = models.CharField(
        max_length=3, choices=HTTP_METHOD_CHOICE, default=HTTP_METHOD_GET
    )
    code = models.TextField()
    active = models.BooleanField(default=True)
    public = models.BooleanField(default=False)
    history = HistoricalRecords()

    def __str__(self) -> str:
        return f"{self.domain.url_name}/{self.url_name}"

    @property
    def full_url(self):
        return f"/api/{self.domain.url_name}/{self.url_name}/"

    def get_html_hyperlink(self) -> str:
        function_link = reverse("api_engine:function", args=(self.id,))
        return f"<a href='{function_link}'>{self.name}</a>"

    @property
    def swagger_doc_url(self):
        return f"{settings.SWAGGER_URL_TO_DOC}?url={self.full_url}" + "doc/"

    @cached_property
    def has_request_class(self):
        return FUNCTION_REQUEST_CLASS_NAME in self.code

    @cached_property
    def has_response_class(self):
        return FUNCTION_REQUEST_CLASS_NAME in self.code

    def execute(self, request, customer=None, *args, **kwargs) -> Any:
        stdout = StringIO()
        stderr = StringIO()
        with redirect_stdout(stdout):
            exec(self.code, globals())
            try:
                response_data = main(request, *args, **kwargs)
                if isinstance(response_data, tuple):
                    return_data, status_code = response_data
                else:
                    return_data = response_data
                    status_code = 200
            except Exception as ex:
                status_code = 400
                return_data = {"error": str(ex)}
                with redirect_stdout(stderr):
                    traceback.print_exc(file=sys.stdout)

        script_log = stdout.getvalue() + stderr.getvalue()
        FunctionServiceExecution.objects.create(
            function_service=self,
            output=script_log,
            response=return_data,
            request=request.body or request.GET or request.POST,
            customer=customer,
            status_code=status_code,
        )
        return status_code, return_data

    class Meta:
        db_table = "function_service"


class Customer(models.Model):
    name = models.CharField(max_length=500)
    team = models.ForeignKey(Team, on_delete=models.DO_NOTHING)
    created_date = models.DateTimeField(auto_now_add=True)
    last_updated_date = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
        related_name="customer_created_by",
    )
    last_updated_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
        related_name="customer_last_updated_by",
    )
    history = HistoricalRecords()

    def __str__(self) -> str:
        return self.name

    def get_html_hyperlink(self) -> str:
        customer_link = reverse("api_engine:customer", args=(self.id,))
        return f"<a href='{customer_link}'>{self.name}</a>"

    class Meta:
        db_table = "customer"


class CustomerFunctionToken(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    token_id = models.CharField(max_length=100)
    function_service = models.ForeignKey(FunctionService, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    last_updated_date = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
        related_name="customer_function_token_created_by",
    )
    last_updated_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
        related_name="customer_function_token_last_updated_by",
    )
    history = HistoricalRecords()

    def __str__(self) -> str:
        return f"{self.id} - {self.customer.name}"

    class Meta:
        db_table = "customer_function_token"


class FunctionServiceEnvironmentVariable(models.Model):
    function_service = models.ForeignKey(FunctionService, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    value = models.CharField(max_length=500)
    history = HistoricalRecords()

    def __str__(self) -> str:
        return self.name

    def save(self, *args, **kwargs):
        old_schedule_env = FunctionServiceEnvironmentVariable.objects.filter(
            id=self.id
        ).first()
        old_value = old_schedule_env.value if old_schedule_env else ""
        if self.value != old_value:
            self.value = signing.dumps(self.value)
        return super().save(*args, **kwargs)

    @property
    def load_value(self) -> str:
        return signing.loads(self.value)

    class Meta:
        db_table = "function_service_environment_variable"


class FunctionServiceExecution(models.Model):
    function_service = models.ForeignKey(FunctionService, on_delete=models.CASCADE)
    created_dt = models.DateTimeField(auto_now_add=True)
    output = models.TextField(blank=True, null=True)
    response = models.TextField(blank=True, null=True)
    request = models.TextField(blank=True, null=True)
    customer = models.ForeignKey(
        Customer, blank=True, null=True, on_delete=models.DO_NOTHING
    )
    status_code = models.IntegerField(blank=True, null=True)

    def get_html_hyperlink(self) -> str:
        function_link = reverse("api_engine:function-execution", args=(self.id,))
        return f"<a href='{function_link}'>{self.id}</a>"

    def get_badge_status_code(self) -> str:
        badge_status = "info"
        if self.status_code:
            if self.status_code >= 200 and self.status_code < 300:
                badge_status = "success"
            elif self.status_code >= 300 and self.status_code < 400:
                badge_status = "warning"
            elif self.status_code >= 400 and self.status_code < 600:
                badge_status = "danger"
        badge = f"<span class='badge bg-{badge_status}'>{self.status_code}</span>"
        return badge

    def __str__(self) -> str:
        return self.function_service.name

    class Meta:
        db_table = "function_service_execution"

app/api_engine/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from core.models import Team
from .models import (
    FunctionService,
    DomainFunctionService,
    FunctionServiceEnvironmentVariable,
    Customer,
)
from core.utils import get_user_team
from .choices import HTTP_METHOD_CHOICE


class FunctionServiceForm(forms.Form):
    name = forms.CharField(label="Nome", required=False, widget=forms.TextInput())
    description = forms.CharField(
        label="Descrição",
        required=False,
        widget=forms.Textarea(attrs={"rows": 4}),
    )
    domain = forms.ModelChoiceField(
        queryset=DomainFunctionService.objects.all().order_by(
            "name"
        ),  # .filter(user=self.request.user))
        # label=_("Time"), # aplica translate
        label="Domínio",
        widget=forms.Select(),
    )
    http_method = forms.ChoiceField(
        choices=HTTP_METHOD_CHOICE,
        label="Método",
        widget=forms.Select(),
    )
    url_name = forms.CharField(label="Nome URL", widget=forms.TextInput())
    code = forms.CharField(
        label="Code",
        required=False,
        widget=forms.Textarea(attrs={"rows": 10, "class": "python-editor"}),
    )
    team = forms.ModelChoiceField(
        queryset=Team.objects.all().order_by(
            "name"
        ),  # .filter(user=self.request.user))
        # label=_("Time"), # aplica translate
        label="Time",
        required=False,
        widget=forms.Select(attrs={"class": "form-control"}),
    )
    active = forms.BooleanField(
        label="&nbsp Ativo",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-control"}),
    )
    public = forms.BooleanField(
        label="&nbsp API Pública",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-control"}),
    )

    class Meta:
        model = FunctionService

    def __init__(self, user=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if kwargs:
            self.fields["team"].widget.attrs["disabled"] = "true"
        if user:
            self.fields["team"].queryset = Team.objects.filter(user=user).order_by(
                "name"
            )
            self.fields["domain"].queryset = DomainFunctionService.objects.filter(
                team__in=get_user_team(user)
            ).order_by("name")


class FunctionServiceEnvironmentVariableForm(forms.Form):
    name = forms.CharField(label="Nome", required=True, widget=forms.TextInput())
    value = forms.CharField(
        label="Descrição",
        required=True,
        widget=forms.TextInput(),
    )

    class Meta:
        model = FunctionServiceEnvironmentVariable


class DomainFunctionServiceForm(forms.Form):
    name = forms.CharField(label="Nome", required=True, widget=forms.TextInput())
    url_name = forms.CharField(
        label="Nome URL", required=True, widget=forms.TextInput()
    )
    team = forms.ModelChoiceField(
        queryset=Team.objects.all().order_by(
            "name"
        ),  # .filter(user=self.request.user))
        # label=_("Time"), # aplica translate
        label="Time",
        required=False,
        widget=forms.Select(attrs={"class": "form-control"}),
    )
    active = forms.BooleanField(
        label="&nbsp Ativo",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-control"}),
    )

    class Meta:
        model = DomainFunctionService

    def __init__(self, user=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if kwargs:
            self.fields["team"].widget.attrs["disabled"] = "true"
        if user:
            self.fields["team"].queryset = Team.objects.filter(user=user).order_by(
                "name"
            )


class CustomerForm(forms.Form):
    name = forms.CharField(label="Nome", required=True, widget=forms.TextInput())
    team = forms.ModelChoiceField(
        queryset=Team.objects.all().order_by(
            "name"
        ),  # .filter(user=self.request.user))
        # label=_("Time"), # aplica translate
        label="Time",
        required=False,
        widget=forms.Select(attrs={"class": "form-control"}),
    )

    class Meta:
        model = Customer

    def __init__(self, user=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if kwargs:
            self.fields["team"].widget.attrs["disabled"] = "true"
        if user:
            self.fields["team"].queryset = Team.objects.filter(user=user).order_by(
                "name"
            )

app/api_engine/templates/function/customers-tab.html
<div class="card-body">
    {% if form.erros %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
    {% endif %}


    {% for cf in extra.customer_function %} 
        <div class="row">                                  
            <div class="form-group col-6">
                <label for="customer" class="form-label">Parceiro</label>
                <input type="text" value="{{ cf.customer.name }}" id="customer" class="textinput textInput form-control" disabled>
            </div>                      
            <input type="hidden" id="customer-name-{{ cf.customer.id }}" class="form-control" value="{{ cf.customer.name }}">
            <input type="hidden" id="customer-token-{{ cf.customer.id }}" class="form-control" value="{{ cf.token_id }}">       
            {% if perms.api_engine.change_api %}                   
            <div class="form-group col-4" style="margin-top: 30px">
                <button type="button" class="btn btn-warning btn-edit-customer" data-bs-toggle="modal" data-bs-target="#modal-customer" 
                        id="btn-edit-customer" customer-id="{{ cf.customer.id }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></svg>
                </button>                                
                <button type="button" class="btn btn-danger btn-remove-customer" data-bs-toggle="modal" data-bs-target="#modal-remove-customer" 
                        id="btn-remove-customer" customer-id="{{ cf.customer.id }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-minus"><line x1="5" y1="12" x2="19" y2="12"></line></svg>
                </button>  
            </div>
            {% endif %}
        </div>                     
    {% endfor %}   
    {% if perms.api_engine.change_api %}   
    <div class="form-group col-4" style="margin-top: 30px">
        <button type="button" class="btn btn-success btn-add-customer" data-bs-toggle="modal" data-bs-target="#modal-new-customer">Adicionar</button>                                
    </div>
    {% endif %}


    <!--Modal Generate new token -->
    <div class="modal fade text-left modal-borderless" id="modal-customer"
        tabindex="-1" role="dialog" aria-labelledby="myModalLabel1"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-scrollable" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Dados Acesso - Parceiro</h5>
                    <button type="button" class="close rounded-pill"
                        data-bs-dismiss="modal" aria-label="Close">
                        <i data-feather="x"></i>
                    </button>
                </div>
                <form action={% if extra.function %}{% url 'api_engine:function-customer' extra.function.id %}{% endif %}
                        method='PUT'>{% csrf_token %}
                    <input type="hidden" name="method" value="PUT">
                    <div class="modal-body">
                        <div class="row">                                  
                            <div class="form-group col-">
                                <label for="customer-name-select" class="form-label">Parceiro</label>
                                    <select class="form-control select form-select" id="customer-name-select" disabled>
                                        <option value="">---------</option>
                                        {% for customer in extra.customers %}
                                            <option value="{{ customer.id }}">{{ customer.name }}</option>
                                        {% endfor %}
                                    </select>                              
                            </div>        
                            <input type="text" id="customer-id" name="customer_id" class="textinput textInput form-control" hidden>                                        
                        </div>  
                        <div class="row">
                            <div class="form-group col-">
                                <label for="customer-token" class="form-label">Token</label>
                                <input type="text" id="customer-token" name="value" class="textinput textInput form-control" disabled>
                            </div>  
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger"
                            data-bs-dismiss="modal">
                            <i class="bx bx-x d-block d-sm-none"></i>
                            <span class="d-none d-sm-block">Cancelar</span>
                        </button>
                        <button type="submit" class="btn btn-success ml-1">
                            <i class="bx bx-check d-block d-sm-none"></i>
                            <span class="d-none d-sm-block">Regerar Token</span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>      


    <!--Modal Exclui Variável de Ambiente -->
    <div class="modal fade text-left" id="modal-remove-customer" tabindex="-1"
        role="dialog" aria-labelledby="myModalLabel120"
        aria-hidden="true">
        <form action={% if extra.function %}{% url 'api_engine:function-customer' extra.function.id %}{% endif %} method='DELETE'>{% csrf_token %}
            <input type="hidden" class="form-control" name="customer_id" id="customer-id-to-remove">
            <input type="hidden" name="method" value="DELETE">
            <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable"
                role="document">
                <div class="modal-content">
                    <div class="modal-header bg-danger">
                        <h5 class="modal-title white" id="title-remove-env">
                            Parceiro</h5>
                        <button type="button" class="close"
                            data-bs-dismiss="modal" aria-label="Close">
                            <i data-feather="x"></i>
                        </button>
                    </div>
                    <div class="modal-body">
                        Tem certeza que deseja remover esse parceiro da API?
                    </div>
                    <div class="modal-footer">
                        <button type="button"
                            class="btn btn-light-secondary"
                            data-bs-dismiss="modal">
                            <i class="bx bx-x d-block d-sm-none"></i>
                            <span class="d-none d-sm-block">Cancelar</span>
                        </button>
                        <button type="submit" class="btn btn-danger ml-1" value="delete">
                            <i class="bx bx-check d-block d-sm-none"></i>
                            <span class="d-none d-sm-block">Excluir</span>
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

    <!--Modal Add Customer Token-->
    <div class="modal fade text-left modal-borderless" id="modal-new-customer"
        tabindex="-1" role="dialog" aria-labelledby="myModalLabel1"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-scrollable" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Associar Parceiro</h5>
                    <button type="button" class="close rounded-pill"
                        data-bs-dismiss="modal" aria-label="Close">
                        <i data-feather="x"></i>
                    </button>
                </div>
                <form action={% if extra.function %}{% url 'api_engine:function-customer' extra.function.id %}{% endif %}
                        method='POST'>{% csrf_token %}
                    <div class="modal-body">
                        <div class="row">                                  
                            <div class="form-group col-">
                                <label for="customer-id-to-add" class="form-label">Parceiro</label>
                                    <select name="customer_id" class="form-control select form-select" id="customer-id-to-add" required>
                                        <option value="">---------</option>
                                        {% for customer in extra.customers %}
                                            <option value="{{ customer.id }}">{{ customer.name }}</option>
                                        {% endfor %}
                                    </select>                              
                            </div>                                                
                        </div>  
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger"
                            data-bs-dismiss="modal">
                            <i class="bx bx-x d-block d-sm-none"></i>
                            <span class="d-none d-sm-block">Cancelar</span>
                        </button>
                        <button type="submit" class="btn btn-success ml-1">
                            <i class="bx bx-check d-block d-sm-none"></i>
                            <span class="d-none d-sm-block">Salvar</span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>  
{% block script %}
<script>
    $('.btn-edit-customer').click(function (event) {
        let customer_id = $(this).attr("customer-id");
        let customer_token_id = "#customer-token-" + customer_id
        let token = $(customer_token_id).val();
        $("#customer-name-select").val(customer_id).change();  
        $("#customer-token").val(token);      
        $("#customer-id").val(customer_id);      
    });
    
    $('.btn-remove-customer').click(function (event) {
        let customer_id = $(this).attr("customer-id");
        $("#customer-id-to-remove").val(customer_id);
    });  
</script>
{% endblock %}

app/api_engine/templates/function/function-list.html
{% extends "model-page.html"%}
{% block content %}
{% load i18n %}
{% load static %}
{% load list_extras %}
{% load execution_extras %}



<div class="page-title">
    <h3>{% translate "APIs" %}</h3>
</div>
<section class="section">

    <div class="card">
        <div class="card-header">
            Lista de APIs
        </div>
        <div class="card-body">
            <form>
                <div class="form-group mb-1">
                    <input class="form-control" type="text" name="name" placeholder="Buscar por nome...">            
                </div>
                <button type="submit" class="btn btn-primary">Buscar</button>
            <form>

            <table class="table table-striped mt-4 table-responsive-md">
                <thead>
                    <tr>
                        <th>
                            <a class="text-green" href="{% order_by_href "name" request.GET.order_by request.GET.name %}">
                            {% order_by "name" request.GET.order_by as arrow_name %}
                            {{ arrow_name | safe}}
                            Função 
                            </a>
                        </th>
                        <th>
                            <a class="text-green"  href="{% order_by_href "domain__name" request.GET.order_by request.GET.name %}">
                            {% order_by "domain__name" request.GET.order_by as arrow_domain %}
                            {{ arrow_domain | safe}}
                            Domínio
                            </a>
                        </th>
                        <th>
                            <a class="text-green"  href="{% order_by_href "domain__name" request.GET.order_by request.GET.name %}">
                            {% order_by "domain__name" request.GET.order_by as arrow_domain__name %}
                            {{ arrow_domain__name | safe}}
                            URL
                            </a>
                        </th>
                        <th>
                            <a class="text-green"  href="{% order_by_href "method" request.GET.order_by request.GET.name %}">
                            {% order_by "method" request.GET.order_by as arrow_method %}
                            {{ arrow_method | safe}}
                            Método
                            </a>
                        </th>
                        <th>
                            <a class="text-green"  href="{% order_by_href "team__name" request.GET.order_by %}">
                            {% order_by "team__name" request.GET.order_by as arrow_team %}
                            {{ arrow_team | safe}}
                            Time
                            </a>
                        </th>
                        <th>
                            <a class="text-green"  href="{% order_by_href "active" request.GET.order_by %}">
                            {% order_by "active" request.GET.order_by as arrow_active %}
                            {{ arrow_active | safe}}
                            Status
                            </a>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for function in object_list %}
                        <tr>
                            <td>{{ function.get_html_hyperlink|safe }}</a></td>
                            <td>{{ function.domain.name | safe }}</td>
                            <td>{{ function.full_url }}</td>
                            <td>{{ function.get_http_method_display }}</td>
                            <td>{{ function.team.name }}</td>
                            <td>
                                {% if function.active %}
                                    <span class="badge bg-success">Active</span>
                                {% else %}
                                    <span class="badge bg-danger">Disabled</span>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

            
            {% include "pagination.html" %}
        </div>
    </div>
</section>

{% endblock %}