app/core/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from django.contrib.auth.decorators import login_required
from . import views
from .views import LoginView, index, LogoutView, ChangePasswordView


urlpatterns = [
    path("", RedirectView.as_view(url="index", permanent=False)),
    path("index/", login_required(index), name="index"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("change-password/", ChangePasswordView.as_view(), name="change-password"),
]

app/ia_engine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from core import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    #path("", views.index, name="index"),
    #path("", RedirectView.as_view(url="index", permanent=False)),
    #path("core", include("core.urls")),
    path("task_engine/", include("task_engine.urls")),
    path("api/", include("api_engine.urls_functions")),
    path("api_engine/", include("api_engine.urls")),
]

app/task_engine/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    ScheduleListView,
    ScheduleView,
    EnvironmentVariableView,
    ActionListView,
    ActionView,
    ScheduleExecutionListView,
    ScheduleExecutionView,
    TicketView,
    TicketListView,
    ReprocessTicketView,
    ForceExecutionScheduleView,
    graphics_bar_per_schedule,
    graphics_bar_ticket_per_schedule,
    graphics_area_schedule_per_time,
    graphics_area_ticket_per_time,
)

app_name = "task_engine"

urlpatterns = [
    path(
        "schedule/list/",
        login_required(ScheduleListView.as_view()),
        name="schedule-list",
    ),
    path("schedule/", login_required(ScheduleView.as_view()), name="schedule"),
    path(
        "schedule/<int:schedule_id>",
        login_required(ScheduleView.as_view()),
        name="schedule",
    ),
    path(
        "environment-variables/<int:schedule_id>",
        login_required(EnvironmentVariableView.as_view()),
        name="environment-variable",
    ),
    path("step/", login_required(ScheduleView.as_view()), name="step"),
    path("action/list/", login_required(ActionListView.as_view()), name="action-list"),
    path("action/", login_required(ActionView.as_view()), name="action"),
    path("action/<int:action_id>", login_required(ActionView.as_view()), name="action"),
    path(
        "schedule/execution/list/",
        login_required(ScheduleExecutionListView.as_view()),
        name="schedule-execution-list",
    ),
    path(
        "schedule/execution/<int:execution_id>",
        login_required(ScheduleExecutionView.as_view()),
        name="schedule-execution",
    ),
    path(
        "schedule/graphics_bar/",
        login_required(graphics_bar_per_schedule),
        name="graphics_bar_per_schedule",
    ),
    path(
        "schedule/graphics_area/",
        login_required(graphics_area_schedule_per_time),
        name="graphics_area_schedule_per_time",
    ),
    path(
        "schedule/force_execution/<int:schedule_id>",
        login_required(ForceExecutionScheduleView.as_view()),
        name="schedule-force-execution",
    ),
    path("ticket/list/", login_required(TicketListView.as_view()), name="ticket-list"),
    path("ticket/<int:ticket_id>", login_required(TicketView.as_view()), name="ticket"),
    path(
        "ticket/reprocess/<int:ticket_id>",
        login_required(ReprocessTicketView.as_view()),
        name="reprocess_ticket",
    ),
    path(
        "ticket/graphics_bar/",
        login_required(graphics_bar_ticket_per_schedule),
        name="graphics_bar_ticket_per_schedule",
    ),
    path(
        "ticket/graphics_area/",
        login_required(graphics_area_ticket_per_time),
        name="graphics_area_ticket_per_time",
    ),
]

app/task_engine/models.py
from typing import Dict, Tuple, Any
from io import StringIO
from contextlib import redirect_stdout
from simple_history.models import HistoricalRecords


from django.urls import reverse
from django.core import signing
from django.db import models
from django.contrib.auth.models import User

from core.models import Team
from .choices import (
    EXECUTION_STATUS_CHOICE,
    EXECUTION_STATUS_PENDING,
    NOTIFICATION_TYPE_CHOICE,
    NOTIFICATION_TYPE_NEVER,
)

import sys
import traceback


class Script(models.Model):
    code = models.TextField()
    history = HistoricalRecords()

    def __str__(self) -> str:
        return str(self.id)

    def get_output(self, binds):
        return self.output.format(**binds)

    def execute(self, parm: Dict = {}) -> Tuple[bool, Any, str]:
        stdout = StringIO()
        stderr = StringIO()
        return_data = []
        control_value = ""
        with redirect_stdout(stdout):
            try:
                exec(self.code, globals())
                result = main(**parm)
                if isinstance(result, tuple):
                    return_data, control_value = result
                else:
                    return_data = result
            except Exception:
                with redirect_stdout(stderr):
                    traceback.print_exc(file=sys.stdout)
        script_log = stdout.getvalue() + stderr.getvalue()
        status = not bool(stderr.getvalue())
        return status, return_data, script_log, str(control_value)

    class Meta:
        db_table = "script"


class Schedule(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    last_updated_date = models.DateTimeField(auto_now=True)
    days = models.IntegerField(null=True, blank=True, default=0)
    hours = models.IntegerField(null=True, blank=True, default=0)
    minutes = models.IntegerField(null=True, blank=True, default=0)
    cron = models.CharField(max_length=20, null=True, blank=True)
    last_execution = models.DateTimeField(null=True, blank=True)
    last_value = models.CharField(max_length=100, null=True, blank=True)
    active = models.BooleanField(default=True)
    created_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
        related_name="schedule_created_by",
    )
    last_updated_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
        related_name="schedule_last_updated_by",
    )
    script = models.ForeignKey(Script, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.DO_NOTHING)
    notification_type = models.CharField(
        max_length=2, choices=NOTIFICATION_TYPE_CHOICE, default=NOTIFICATION_TYPE_NEVER
    )
    emails_to_notification = models.CharField(max_length=2000, null=True, blank=True)
    history = HistoricalRecords()

    def __str__(self) -> str:
        return self.name
        # return super().__str__()

    def get_html_hyperlink(self) -> str:
        schedule_link = reverse("task_engine:schedule", args=(self.id,))
        return f"<a href='{schedule_link}'>{self.name}</a>"

    class Meta:
        db_table = "schedule"


class Action(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=100)
    script = models.ForeignKey(Script, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    last_updated_date = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
        related_name="action_created_by",
    )
    last_updated_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
        related_name="action_last_updated_by",
    )
    active = models.BooleanField(default=True)
    team = models.ForeignKey(Team, on_delete=models.DO_NOTHING)
    history = HistoricalRecords()

    def __str__(self) -> str:
        return self.name
        # return super().__str__()

    def get_html_hyperlink(self) -> str:
        action_link = reverse("task_engine:action", args=(self.id,))
        return f"<a href='{action_link}'>{self.name}</a>"

    class Meta:
        db_table = "action"


class StepSchedule(models.Model):
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE)
    action = models.ForeignKey(Action, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    last_updated_date = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
        related_name="step_created_by",
    )
    last_updated_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
        related_name="steo_last_updated_by",
    )
    execution_order = models.IntegerField(default=0)
    stoppable = models.BooleanField(default=True)
    history = HistoricalRecords()

    def __str__(self) -> str:
        return self.action.name
        # return super().__str__()

    class Meta:
        db_table = "step_schedule"


class ScheduleExecution(models.Model):
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE)
    execution_status = models.CharField(
        max_length=2, choices=EXECUTION_STATUS_CHOICE, default=EXECUTION_STATUS_PENDING
    )
    execution_log = models.TextField(blank=True, null=True)
    execution_date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.schedule.name} - {self.execution_status}"

    def get_html_hyperlink(self) -> str:
        schedule_execution_link = reverse(
            "task_engine:schedule-execution", args=(self.id,)
        )
        return f"<a href='{schedule_execution_link}'>{self.id}</a>"

    class Meta:
        db_table = "schedule_execution"


class Ticket(models.Model):
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE)
    schedule_execution = models.ForeignKey(
        ScheduleExecution, on_delete=models.CASCADE, blank=True, null=True
    )
    created_date_ticket = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    execution_status = models.CharField(
        max_length=2, choices=EXECUTION_STATUS_CHOICE, default=EXECUTION_STATUS_PENDING
    )
    external_id = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.id} - {self.schedule.name} - {self.execution_status}"

    def get_html_hyperlink(self) -> str:
        ticket_link = reverse("task_engine:ticket", args=(self.id,))
        # schedule_link = reverse("schedule", args=(self.id, ))
        return f"<a href='{ticket_link}'>{self.id}</a>"

    class Meta:
        db_table = "ticket"


class TicketParameter(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    value = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        value = self.value[0:50]
        if len(self.value) > 50:
            value += "..."
        return f"{self.ticket.id} - {self.name} - {value}"

    class Meta:
        db_table = "ticket_parameter"


class TicketActionLog(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    action = models.ForeignKey(Action, on_delete=models.DO_NOTHING)
    execution_log = models.TextField(blank=True, null=True)
    execution_date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.ticket.id} - {self.action.name}"

    class Meta:
        db_table = "ticket_action_log"


class ScheduleEnvironmentVariable(models.Model):
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    value = models.CharField(max_length=500)
    history = HistoricalRecords()

    def __str__(self) -> str:
        return self.name

    def save(self, *args, **kwargs):
        old_schedule_env = ScheduleEnvironmentVariable.objects.filter(
            id=self.id
        ).first()
        old_value = old_schedule_env.value if old_schedule_env else ""
        if self.value != old_value:
            self.value = signing.dumps(self.value)
        return super().save(*args, **kwargs)

    @property
    def load_value(self) -> str:
        return signing.loads(self.value)

    class Meta:
        db_table = "schedule_environment_variable"


class TeamWorker(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    suffix_worker_name = models.CharField(max_length=50)
    active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    last_updated_date = models.DateTimeField(auto_now=True)
    concurrency = models.IntegerField()
    history = HistoricalRecords()

    def __str__(self) -> str:
        return f"{self.team.name}"

    class Meta:
        db_table = "team_worker"

app/task_engine/templates/actions/action.html
{% extends "model-page.html"%}
{% block content %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

<link rel="stylesheet" href="{% static '/vendors/codemirror/lib/codemirror.css' %}">
<script src="{% static '/vendors/codemirror/lib/codemirror.js' %}"></script>
<script src="{% static '/vendors/codemirror/mode/python/python.js' %}"></script>
<script src="{% static '/vendors/codemirror/addon/selection/active-line.js' %}"></script>
<link rel="stylesheet" href="{% static '/vendors/codemirror/theme/monokai.css' %}">
<link rel="stylesheet" href="{% static '/vendors/codemirror/theme/darcula.css' %}">
<link rel="stylesheet" href="{% static '/vendors/codemirror/theme/dracula.css' %}">
<link rel="stylesheet" href="{% static '/vendors/codemirror/theme/colorforth.css' %}">
<link rel="stylesheet" href="{% static '/vendors/codemirror/theme/eclipse.css' %}">

<style>
.CodeMirror {border: 1px solid #aaa;}
</style>

<div class="page-title">
    <h3>{% translate "Ação" %}</h3>
</div>
<section class="section">
    <div class="card">
        {% comment %} <div class="card-header">
            Ação
        </div> {% endcomment %}




        <div class="card-body">
            {% if form.erros %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
            {% endif %}
            {% if messages %}
                <div class="row">
                    <ul class="messages">
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                                <strong>{{ message }}</strong>
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            <form action=
                    {% if action%}
                        {% url 'task_engine:action' action.id %}
                    {% else %}
                        {% url 'task_engine:action' %}
                    {% endif %}
                    method='POST'>{% csrf_token %}
        
                {{ form.name|as_crispy_field }}
                {{ form.description|as_crispy_field }}

                <div id="div_id_script" class="mb-3">        
                    <label for="id_script" class="form-label">
                        Code
                    </label>              
                    <textarea name="script" cols="40" rows="10" value="{{ extra.script.id }}" class="python-editor textarea form-control" id="id_script">{{ extra.script.code }}</textarea>
                </div>
                

                <div class="row">
                    <div class="form-group col">
                        {{ form.team|as_crispy_field }}
                    </div>   

                </div>                              
                {{ form.active|as_crispy_field }}
                {% if perms.task_engine.change_automation %}
                <button type="submit" class="btn btn-success">{% trans 'Save' %}</button>
                {% endif %}
            </form>            
        </div>
    </div>
</section>

<script>
    let python_editor = document.getElementsByClassName("python-editor");
    
    Array.prototype.forEach.call(python_editor, function(el) {
        var editor = CodeMirror.fromTextArea(el, {
            lineNumbers: true,
            gutters: ["CodeMirror-linenumbers", "breakpoints"],
            styleActiveLine: true,
            matchBrackets: true,
            theme: "default",
            mode: "python",
        });
        editor.save()
    });
    $(".alert-success").fadeTo(2000, 500).slideUp(500, function(){});
</script>

{% endblock %}

app/task_engine/templates/actions/actions-list.html
{% extends "model-page.html"%}
{% block content %}
{% load i18n %}
{% load static %}
{% load list_extras %}



<div class="page-title">
    <h3>{% translate "Ações" %}</h3>
</div>
<section class="section">

    <div class="card">
        <div class="card-header">
            Lista de ações
        </div>
        <div class="card-body">
            <form>
                <div class="form-group mb-1">
                    <input class="form-control" type="text" name="name" placeholder="Buscar por nome...">            
                </div>
                <button type="submit" class="btn btn-primary">Buscar</button>
            <form>
            <table class="table table-striped mt-4 table-responsive-md">
                <thead>
                    <tr>
                        <th>
                            <a class="text-green" href="{% order_by_href "name" request.GET.order_by request.GET.name %}">
                            {% order_by "name" request.GET.order_by as arrow_name %}
                            {{ arrow_name | safe}}
                            Nome 
                            </a>
                        </th>
                        <th>
                            <a class="text-green"  href="{% order_by_href "team__name" request.GET.order_by request.GET.name %}">
                            {% order_by "team__name" request.GET.order_by as arrow_team %}
                            {{ arrow_team | safe}}
                            Time
                            </a>
                        </th>
                        <th>
                            <a class="text-green"  href="{% order_by_href "active" request.GET.order_by request.GET.name %}">
                            {% order_by "active" request.GET.order_by as arrow_status %}
                            {{ arrow_status | safe}}
                            Status
                            </a>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for action in action_list %}
                        <tr>
                            <td>{{ action.get_html_hyperlink | safe }}</a></td>
                            <td>{{ action.team.name }}</td>
                            <td>
                                {% if action.active %}
                                    <span class="badge bg-success">Active</span>
                                {% else %}
                                    <span class="badge bg-danger">Disabled</span>
                                {% endif %}
                            </td>      
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

            
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" 
                        href="?{% get_params_list request.GET %}&page={{ page_obj.previous_page_number }}">Anterior</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">Anterior</a></li>
                {% endif %}

                {% for object in page_obj.paginator.page_range %}
                    <li class="page-item"><a class="page-link" href="?{% get_params_list request.GET %}&page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" 
                        href="?{% get_params_list request.GET %}&page={{ page_obj.next_page_number }}">Próximo</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">Próximo</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</section>

{% endblock %}