app/core/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from django.contrib.auth.decorators import login_required
from . import views
from .views import LoginView, index, LogoutView, ChangePasswordView


urlpatterns = [
    path("", RedirectView.as_view(url="index", permanent=False)),
    path("index/", login_required(index), name="index"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("change-password/", ChangePasswordView.as_view(), name="change-password"),
]

app/ia_engine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from core import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    #path("", views.index, name="index"),
    #path("", RedirectView.as_view(url="index", permanent=False)),
    #path("core", include("core.urls")),
    path("task_engine/", include("task_engine.urls")),
    path("api/", include("api_engine.urls_functions")),
    path("api_engine/", include("api_engine.urls")),
]

app/task_engine/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    ScheduleListView,
    ScheduleView,
    EnvironmentVariableView,
    ActionListView,
    ActionView,
    ScheduleExecutionListView,
    ScheduleExecutionView,
    TicketView,
    TicketListView,
    ReprocessTicketView,
    ForceExecutionScheduleView,
    graphics_bar_per_schedule,
    graphics_bar_ticket_per_schedule,
    graphics_area_schedule_per_time,
    graphics_area_ticket_per_time,
)

app_name = "task_engine"

urlpatterns = [
    path(
        "schedule/list/",
        login_required(ScheduleListView.as_view()),
        name="schedule-list",
    ),
    path("schedule/", login_required(ScheduleView.as_view()), name="schedule"),
    path(
        "schedule/<int:schedule_id>",
        login_required(ScheduleView.as_view()),
        name="schedule",
    ),
    path(
        "environment-variables/<int:schedule_id>",
        login_required(EnvironmentVariableView.as_view()),
        name="environment-variable",
    ),
    path("step/", login_required(ScheduleView.as_view()), name="step"),
    path("action/list/", login_required(ActionListView.as_view()), name="action-list"),
    path("action/", login_required(ActionView.as_view()), name="action"),
    path("action/<int:action_id>", login_required(ActionView.as_view()), name="action"),
    path(
        "schedule/execution/list/",
        login_required(ScheduleExecutionListView.as_view()),
        name="schedule-execution-list",
    ),
    path(
        "schedule/execution/<int:execution_id>",
        login_required(ScheduleExecutionView.as_view()),
        name="schedule-execution",
    ),
    path(
        "schedule/graphics_bar/",
        login_required(graphics_bar_per_schedule),
        name="graphics_bar_per_schedule",
    ),
    path(
        "schedule/graphics_area/",
        login_required(graphics_area_schedule_per_time),
        name="graphics_area_schedule_per_time",
    ),
    path(
        "schedule/force_execution/<int:schedule_id>",
        login_required(ForceExecutionScheduleView.as_view()),
        name="schedule-force-execution",
    ),
    path("ticket/list/", login_required(TicketListView.as_view()), name="ticket-list"),
    path("ticket/<int:ticket_id>", login_required(TicketView.as_view()), name="ticket"),
    path(
        "ticket/reprocess/<int:ticket_id>",
        login_required(ReprocessTicketView.as_view()),
        name="reprocess_ticket",
    ),
    path(
        "ticket/graphics_bar/",
        login_required(graphics_bar_ticket_per_schedule),
        name="graphics_bar_ticket_per_schedule",
    ),
    path(
        "ticket/graphics_area/",
        login_required(graphics_area_ticket_per_time),
        name="graphics_area_ticket_per_time",
    ),
]

app/task_engine/models.py
from typing import Dict, Tuple, Any
from io import StringIO
from contextlib import redirect_stdout
from simple_history.models import HistoricalRecords


from django.urls import reverse
from django.core import signing
from django.db import models
from django.contrib.auth.models import User

from core.models import Team
from .choices import (
    EXECUTION_STATUS_CHOICE,
    EXECUTION_STATUS_PENDING,
    NOTIFICATION_TYPE_CHOICE,
    NOTIFICATION_TYPE_NEVER,
)

import sys
import traceback


class Script(models.Model):
    code = models.TextField()
    history = HistoricalRecords()

    def __str__(self) -> str:
        return str(self.id)

    def get_output(self, binds):
        return self.output.format(**binds)

    def execute(self, parm: Dict = {}) -> Tuple[bool, Any, str]:
        stdout = StringIO()
        stderr = StringIO()
        return_data = []
        control_value = ""
        with redirect_stdout(stdout):
            try:
                exec(self.code, globals())
                result = main(**parm)
                if isinstance(result, tuple):
                    return_data, control_value = result
                else:
                    return_data = result
            except Exception:
                with redirect_stdout(stderr):
                    traceback.print_exc(file=sys.stdout)
        script_log = stdout.getvalue() + stderr.getvalue()
        status = not bool(stderr.getvalue())
        return status, return_data, script_log, str(control_value)

    class Meta:
        db_table = "script"


class Schedule(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    last_updated_date = models.DateTimeField(auto_now=True)
    days = models.IntegerField(null=True, blank=True, default=0)
    hours = models.IntegerField(null=True, blank=True, default=0)
    minutes = models.IntegerField(null=True, blank=True, default=0)
    cron = models.CharField(max_length=20, null=True, blank=True)
    last_execution = models.DateTimeField(null=True, blank=True)
    last_value = models.CharField(max_length=100, null=True, blank=True)
    active = models.BooleanField(default=True)
    created_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
        related_name="schedule_created_by",
    )
    last_updated_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
        related_name="schedule_last_updated_by",
    )
    script = models.ForeignKey(Script, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.DO_NOTHING)
    notification_type = models.CharField(
        max_length=2, choices=NOTIFICATION_TYPE_CHOICE, default=NOTIFICATION_TYPE_NEVER
    )
    emails_to_notification = models.CharField(max_length=2000, null=True, blank=True)
    history = HistoricalRecords()

    def __str__(self) -> str:
        return self.name
        # return super().__str__()

    def get_html_hyperlink(self) -> str:
        schedule_link = reverse("task_engine:schedule", args=(self.id,))
        return f"<a href='{schedule_link}'>{self.name}</a>"

    class Meta:
        db_table = "schedule"


class Action(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=100)
    script = models.ForeignKey(Script, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    last_updated_date = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
        related_name="action_created_by",
    )
    last_updated_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
        related_name="action_last_updated_by",
    )
    active = models.BooleanField(default=True)
    team = models.ForeignKey(Team, on_delete=models.DO_NOTHING)
    history = HistoricalRecords()

    def __str__(self) -> str:
        return self.name
        # return super().__str__()

    def get_html_hyperlink(self) -> str:
        action_link = reverse("task_engine:action", args=(self.id,))
        return f"<a href='{action_link}'>{self.name}</a>"

    class Meta:
        db_table = "action"


class StepSchedule(models.Model):
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE)
    action = models.ForeignKey(Action, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    last_updated_date = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
        related_name="step_created_by",
    )
    last_updated_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
        related_name="steo_last_updated_by",
    )
    execution_order = models.IntegerField(default=0)
    stoppable = models.BooleanField(default=True)
    history = HistoricalRecords()

    def __str__(self) -> str:
        return self.action.name
        # return super().__str__()

    class Meta:
        db_table = "step_schedule"


class ScheduleExecution(models.Model):
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE)
    execution_status = models.CharField(
        max_length=2, choices=EXECUTION_STATUS_CHOICE, default=EXECUTION_STATUS_PENDING
    )
    execution_log = models.TextField(blank=True, null=True)
    execution_date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.schedule.name} - {self.execution_status}"

    def get_html_hyperlink(self) -> str:
        schedule_execution_link = reverse(
            "task_engine:schedule-execution", args=(self.id,)
        )
        return f"<a href='{schedule_execution_link}'>{self.id}</a>"

    class Meta:
        db_table = "schedule_execution"


class Ticket(models.Model):
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE)
    schedule_execution = models.ForeignKey(
        ScheduleExecution, on_delete=models.CASCADE, blank=True, null=True
    )
    created_date_ticket = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    execution_status = models.CharField(
        max_length=2, choices=EXECUTION_STATUS_CHOICE, default=EXECUTION_STATUS_PENDING
    )
    external_id = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.id} - {self.schedule.name} - {self.execution_status}"

    def get_html_hyperlink(self) -> str:
        ticket_link = reverse("task_engine:ticket", args=(self.id,))
        # schedule_link = reverse("schedule", args=(self.id, ))
        return f"<a href='{ticket_link}'>{self.id}</a>"

    class Meta:
        db_table = "ticket"


class TicketParameter(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    value = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        value = self.value[0:50]
        if len(self.value) > 50:
            value += "..."
        return f"{self.ticket.id} - {self.name} - {value}"

    class Meta:
        db_table = "ticket_parameter"


class TicketActionLog(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    action = models.ForeignKey(Action, on_delete=models.DO_NOTHING)
    execution_log = models.TextField(blank=True, null=True)
    execution_date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.ticket.id} - {self.action.name}"

    class Meta:
        db_table = "ticket_action_log"


class ScheduleEnvironmentVariable(models.Model):
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    value = models.CharField(max_length=500)
    history = HistoricalRecords()

    def __str__(self) -> str:
        return self.name

    def save(self, *args, **kwargs):
        old_schedule_env = ScheduleEnvironmentVariable.objects.filter(
            id=self.id
        ).first()
        old_value = old_schedule_env.value if old_schedule_env else ""
        if self.value != old_value:
            self.value = signing.dumps(self.value)
        return super().save(*args, **kwargs)

    @property
    def load_value(self) -> str:
        return signing.loads(self.value)

    class Meta:
        db_table = "schedule_environment_variable"


class TeamWorker(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    suffix_worker_name = models.CharField(max_length=50)
    active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    last_updated_date = models.DateTimeField(auto_now=True)
    concurrency = models.IntegerField()
    history = HistoricalRecords()

    def __str__(self) -> str:
        return f"{self.team.name}"

    class Meta:
        db_table = "team_worker"

app/task_engine/templates/schedule/environment.html
<div class="card-body">
    {% if form.erros %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
    {% endif %}


                    
    {% for environment in extra.environment_variable %} 
        <div class="row">                                  
            <div class="form-group col-6">
                <label for="environment_key" class="form-label">Chave</label>
                <input type="text" value={{ environment.name }} id="environment_key" class="textinput textInput form-control" disabled>
            </div>                      
            <input type="hidden" id="env-key-{{ environment.id }}" class="form-control" value="{{ environment.name }}">
            <input type="hidden" id="env-value-{{ environment.id }}" class="form-control" value="{{ environment.load_value }}">                          
            <div class="form-group col-4" style="margin-top: 30px">
                <button type="button" class="btn btn-warning btn-edit-env" data-bs-toggle="modal" data-bs-target="#modal-environment" 
                        id="btn-edit-env" env-id="{{ environment.id }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></svg>
                </button>                                
                <button type="button" class="btn btn-danger btn-remove-env" data-bs-toggle="modal" data-bs-target="#modal-remove-environment" 
                        id="btn-remove-env" env-id="{{ environment.id }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-minus"><line x1="5" y1="12" x2="19" y2="12"></line></svg>
                </button>  
            </div>
        </div>                     
    {% endfor %}   
    <div class="form-group col-4" style="margin-top: 30px">
        <button type="button" class="btn btn-success btn-add-environment" data-bs-toggle="modal" data-bs-target="#modal-environment">Adicionar</button>                                
    </div>


    <!--Modal Variável de Ambiente -->
    <div class="modal fade text-left modal-borderless" id="modal-environment"
        tabindex="-1" role="dialog" aria-labelledby="myModalLabel1"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-scrollable" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Variável de Ambiente</h5>
                    <button type="button" class="close rounded-pill"
                        data-bs-dismiss="modal" aria-label="Close">
                        <i data-feather="x"></i>
                    </button>
                </div>
                <form action={% if schedule %}{% url 'task_engine:environment-variable' schedule.id %}{% endif %}
                        method='POST'>{% csrf_token %}
                    <input type="hidden" class="form-control" name="environment_id" id="environment-id">
                    <div class="modal-body">
                        <div class="row">                                  
                            <div class="form-group col-">
                                <label for="environment_name" class="form-label">Chave</label>
                                <input type="text" id="environment-key" name="name" class="textinput textInput form-control">
                            </div>                                                
                        </div>  
                        <div class="row">
                            <div class="form-group col-">
                                <label for="environment_name" class="form-label">Valor</label>
                                <input type="text" id="environment-value" name="value" class="textinput textInput form-control">
                            </div>  
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger"
                            data-bs-dismiss="modal">
                            <i class="bx bx-x d-block d-sm-none"></i>
                            <span class="d-none d-sm-block">Cancelar</span>
                        </button>
                        <button type="submit" class="btn btn-success ml-1">
                            <i class="bx bx-check d-block d-sm-none"></i>
                            <span class="d-none d-sm-block">Salvar</span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>      


    <!--Modal Exclui Variável de Ambiente -->
    <div class="modal fade text-left" id="modal-remove-environment" tabindex="-1"
        role="dialog" aria-labelledby="myModalLabel120"
        aria-hidden="true">
        <form action={% if schedule %}{% url 'task_engine:environment-variable' schedule.id %}{% endif %} method='DELETE'>{% csrf_token %}
            <input type="hidden" class="form-control" name="environment_id" id="environment-id-to-remove">
            <input type="hidden" name="method" value="DELETE">
            <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable"
                role="document">
                <div class="modal-content">
                    <div class="modal-header bg-danger">
                        <h5 class="modal-title white" id="title-remove-env">
                            Variável de Ambiente</h5>
                        <button type="button" class="close"
                            data-bs-dismiss="modal" aria-label="Close">
                            <i data-feather="x"></i>
                        </button>
                    </div>
                    <div class="modal-body">
                        Tem certeza que deseja remover essa variável de ambiente?
                    </div>
                    <div class="modal-footer">
                        <button type="button"
                            class="btn btn-light-secondary"
                            data-bs-dismiss="modal">
                            <i class="bx bx-x d-block d-sm-none"></i>
                            <span class="d-none d-sm-block">Cancelar</span>
                        </button>
                        <button type="submit" class="btn btn-danger ml-1" value="delete">
                            <i class="bx bx-check d-block d-sm-none"></i>
                            <span class="d-none d-sm-block">Excluir</span>
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

{% block script %}
<script>
    $('.btn-edit-env').click(function (event) {
        let env_id = $(this).attr("env-id");
        let env_key_id = "env-key-" + env_id
        let env_value_id= "env-value-" + env_id
        let env_key = document.getElementById(env_key_id).value;
        let env_value = document.getElementById(env_value_id).value;
        document.getElementById("environment-key").value = env_key;
        document.getElementById("environment-value").value = env_value;
        document.getElementById("environment-id").value = env_id;
        
    });

    $('.btn-add-environment').click(function (event) {
        document.getElementById("environment-key").value = "";
        document.getElementById("environment-value").value = "";
        document.getElementById("environment-id").value = "";
    });

    $('.btn-remove-env').click(function (event) {
        let env_id = $(this).attr("env-id");
        let env_key_id = "env-key-" + env_id
        let env_key = document.getElementById(env_key_id).value;
        $('#title-remove-env').html("Excluir '" + env_key + "'");
        document.getElementById("environment-id-to-remove").value = env_id;
    });  
    

</script>
{% endblock %}

app/task_engine/templates/schedule/execution.html
{% extends "model-page.html"%}
{% block content %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
{% load execution_extras %}

<link rel="stylesheet" href="{% static '/vendors/codemirror/lib/codemirror.css' %}">
<script src="{% static '/vendors/codemirror/lib/codemirror.js' %}"></script>
<script src="{% static '/vendors/codemirror/mode/python/python.js' %}"></script>
<script src="{% static '/vendors/codemirror/addon/selection/active-line.js' %}"></script>
<link rel="stylesheet" href="{% static '/vendors/codemirror/theme/monokai.css' %}">
<link rel="stylesheet" href="{% static '/vendors/codemirror/theme/darcula.css' %}">
<link rel="stylesheet" href="{% static '/vendors/codemirror/theme/dracula.css' %}">
<link rel="stylesheet" href="{% static '/vendors/codemirror/theme/colorforth.css' %}">
<link rel="stylesheet" href="{% static '/vendors/codemirror/theme/eclipse.css' %}">

<style>
.CodeMirror {border: 1px solid #aaa;}
</style>

<div class="page-title">
    <h3>{% translate "Execução" %}</h3>
</div>
<section class="section">
    <div class="card">
        <div class="card-header">
            Execução
        </div>


        <div class="card-body">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item" role="presentation">
                    <a class="nav-link active" id="home-tab" data-bs-toggle="tab" href="#home"
                        role="tab" aria-controls="home" aria-selected="true">Execução</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link" id="environments-tab" data-bs-toggle="tab" href="#tickets"
                        role="tab" aria-controls="environments" aria-selected="false">Tickets</a>
                </li>
            </ul>
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <div class="card-body">
                        {% if form.erros %}
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <div class="alert alert-danger">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% endfor %}
                        {% endif %}

                        <div class="row mb-5">
                            <div class="col-sm-6 col-lg-6 col-md-6 col-xs-6" align="left">
                                <span class="badge {% badge_status_execution schedule_execution.execution_status %}" style="width: 100px; height: 30px; font-size: 15px">{{ schedule_execution.get_execution_status_display }}</span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-4 col-lg-4 col-md-4 col-xs-4">
                                <b>ID</b>
                            </div>
                            <div class="col-sm-4 col-lg-4 col-md-4 col-xs-4">
                                <b>Data de Execução</b>
                            </div>
                            <div class="col-sm-4 col-lg-4 col-md-4 col-xs-4">
                                <b>Time</b>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-4 col-lg-4 col-md-4 col-xs-4">
                                {{ schedule_execution.id }}
                            </div>
                            <div class="col-sm-4 col-lg-4 col-md-4 col-xs-4">
                                {{ schedule_execution.execution_date }}
                            </div>
                            <div class="col-sm-4 col-lg-4 col-md-4 col-xs-4">
                                {{ schedule_execution.schedule.team.name }}
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12 col-lg-12 col-md-12 col-xs-12">
                                <b>Integração</b>
                            </div>

                        </div>
                        <div class="row mb-3">
                             <div class="col-sm-12 col-lg-12 col-md-12 col-xs-12">
                                {{ schedule_execution.schedule.name }}
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="exampleFormControlTextarea1" class="form-label"><b>Log de Execução</b></label>
                            <textarea class="form-control" rows="10" disabled>{{ schedule_execution.execution_log }}</textarea>
                        </div>   
 
                    
                    </div>
                </div>

                <div class="container-fluid mt-4 ms-2">
                        <h4>Total: {{ tickets|length }}</h4>
                </div>

                <div class="tab-pane fade" id="tickets" role="tabpanel" aria-labelledby="tickets-tab">                    
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Ticket ID</th>
                                        <th>External ID</th>
                                        <th>Status</th>
                                    </tr>
                                </thead>
                            <tbody>
                                {% for ticket in tickets %}
                                <tr>
                                    <td><a href="#">{{ ticket.get_html_hyperlink|safe }}</a></td>
                                    <td>
                                        {% if ticket.external_id %}
                                           {{ ticket.external_id }}
                                        {% else %}
                                            -
                                        {% endif %}
                                    </td>
                                    <td>
                                    <span class="badge {% badge_status_execution ticket.execution_status %}">{{ ticket.get_execution_status_display }}</span>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</section>


{% endblock %}

app/task_engine/templates/schedule/executions-tab.html
{% load execution_extras %}
<div class="card-body">
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Data Execução</th>
                    <th>Status</th>
                </tr>
            </thead>
        <tbody>
            {% for execution in extra.executions %}
            <tr>
                <td>{{ execution.get_html_hyperlink|safe }}</td>
                <td>{{ execution.execution_date }}</td>
                <td><span class="badge {% badge_status_execution execution.execution_status %}">{{ execution.get_execution_status_display }}</span></td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
    </div>
</div>

app/task_engine/templates/schedule/index.html
<html>
    <head>
        <link rel="stylesheet" href="index.css">
        <script src="{% static '/vendors/vuejs/vuejs.js' %}"></script>
    </head>
    <body>
        
        <div id="vue-app">
            [[ message ]]
        </div>
        
        <script>
            var app = new Vue({
                delimiters: ["[[", "]]"],
                el: '#vue-app',
                data: {
                    message: 'Hello Vue!'
                }
            })
        </script>
    </body>
</html>