app/api_engine/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    FunctionListView,
    FunctionView,
    FunctionCustomerView,
    FunctionExecutionListView,
    FunctionExecutionView,
    EnvironmentVariableView,
    DomainListView,
    DomainView,
    CustomerView,
    CustomerListView,
)

app_name = "api_engine"

urlpatterns = [
    path(
        "function/list/",
        login_required(FunctionListView.as_view()),
        name="function-list",
    ),
    path("function/", login_required(FunctionView.as_view()), name="function"),
    path(
        "function/<int:function_id>",
        login_required(FunctionView.as_view()),
        name="function",
    ),
    path(
        "function/<int:function_id>/customer",
        login_required(FunctionCustomerView.as_view()),
        name="function-customer",
    ),
    path(
        "function/execution/list",
        login_required(FunctionExecutionListView.as_view()),
        name="function-execution-list",
    ),
    path(
        "function/execution/<int:execution_id>",
        login_required(FunctionExecutionView.as_view()),
        name="function-execution",
    ),
    path(
        "environment-variables/<int:function_id>",
        login_required(EnvironmentVariableView.as_view()),
        name="environment-variable",
    ),
    path("domain/list/", login_required(DomainListView.as_view()), name="domain-list"),
    path("domain/", login_required(DomainView.as_view()), name="domain"),
    path("domain/<int:domain_id>", login_required(DomainView.as_view()), name="domain"),
    path(
        "customer/list/",
        login_required(CustomerListView.as_view()),
        name="customer-list",
    ),
    path("customer/", login_required(CustomerView.as_view()), name="customer"),
    path(
        "customer/<int:customer_id>",
        login_required(CustomerView.as_view()),
        name="customer",
    ),
]

app/core/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from django.contrib.auth.decorators import login_required
from . import views
from .views import LoginView, index, LogoutView, ChangePasswordView


urlpatterns = [
    path("", RedirectView.as_view(url="index", permanent=False)),
    path("index/", login_required(index), name="index"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("change-password/", ChangePasswordView.as_view(), name="change-password"),
]

app/ia_engine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from core import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    #path("", views.index, name="index"),
    #path("", RedirectView.as_view(url="index", permanent=False)),
    #path("core", include("core.urls")),
    path("task_engine/", include("task_engine.urls")),
    path("api/", include("api_engine.urls_functions")),
    path("api_engine/", include("api_engine.urls")),
]

app/api_engine/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from core.models import Team
from .models import (
    FunctionService,
    DomainFunctionService,
    FunctionServiceEnvironmentVariable,
    Customer,
)
from core.utils import get_user_team
from .choices import HTTP_METHOD_CHOICE


class FunctionServiceForm(forms.Form):
    name = forms.CharField(label="Nome", required=False, widget=forms.TextInput())
    description = forms.CharField(
        label="Descrição",
        required=False,
        widget=forms.Textarea(attrs={"rows": 4}),
    )
    domain = forms.ModelChoiceField(
        queryset=DomainFunctionService.objects.all().order_by(
            "name"
        ),  # .filter(user=self.request.user))
        # label=_("Time"), # aplica translate
        label="Domínio",
        widget=forms.Select(),
    )
    http_method = forms.ChoiceField(
        choices=HTTP_METHOD_CHOICE,
        label="Método",
        widget=forms.Select(),
    )
    url_name = forms.CharField(label="Nome URL", widget=forms.TextInput())
    code = forms.CharField(
        label="Code",
        required=False,
        widget=forms.Textarea(attrs={"rows": 10, "class": "python-editor"}),
    )
    team = forms.ModelChoiceField(
        queryset=Team.objects.all().order_by(
            "name"
        ),  # .filter(user=self.request.user))
        # label=_("Time"), # aplica translate
        label="Time",
        required=False,
        widget=forms.Select(attrs={"class": "form-control"}),
    )
    active = forms.BooleanField(
        label="&nbsp Ativo",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-control"}),
    )
    public = forms.BooleanField(
        label="&nbsp API Pública",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-control"}),
    )

    class Meta:
        model = FunctionService

    def __init__(self, user=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if kwargs:
            self.fields["team"].widget.attrs["disabled"] = "true"
        if user:
            self.fields["team"].queryset = Team.objects.filter(user=user).order_by(
                "name"
            )
            self.fields["domain"].queryset = DomainFunctionService.objects.filter(
                team__in=get_user_team(user)
            ).order_by("name")


class FunctionServiceEnvironmentVariableForm(forms.Form):
    name = forms.CharField(label="Nome", required=True, widget=forms.TextInput())
    value = forms.CharField(
        label="Descrição",
        required=True,
        widget=forms.TextInput(),
    )

    class Meta:
        model = FunctionServiceEnvironmentVariable


class DomainFunctionServiceForm(forms.Form):
    name = forms.CharField(label="Nome", required=True, widget=forms.TextInput())
    url_name = forms.CharField(
        label="Nome URL", required=True, widget=forms.TextInput()
    )
    team = forms.ModelChoiceField(
        queryset=Team.objects.all().order_by(
            "name"
        ),  # .filter(user=self.request.user))
        # label=_("Time"), # aplica translate
        label="Time",
        required=False,
        widget=forms.Select(attrs={"class": "form-control"}),
    )
    active = forms.BooleanField(
        label="&nbsp Ativo",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-control"}),
    )

    class Meta:
        model = DomainFunctionService

    def __init__(self, user=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if kwargs:
            self.fields["team"].widget.attrs["disabled"] = "true"
        if user:
            self.fields["team"].queryset = Team.objects.filter(user=user).order_by(
                "name"
            )


class CustomerForm(forms.Form):
    name = forms.CharField(label="Nome", required=True, widget=forms.TextInput())
    team = forms.ModelChoiceField(
        queryset=Team.objects.all().order_by(
            "name"
        ),  # .filter(user=self.request.user))
        # label=_("Time"), # aplica translate
        label="Time",
        required=False,
        widget=forms.Select(attrs={"class": "form-control"}),
    )

    class Meta:
        model = Customer

    def __init__(self, user=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if kwargs:
            self.fields["team"].widget.attrs["disabled"] = "true"
        if user:
            self.fields["team"].queryset = Team.objects.filter(user=user).order_by(
                "name"
            )

app/api_engine/views.py
from core.models import Team
from django.shortcuts import render, redirect, reverse
from django.views.generic import ListView, View
from django.http import (
    JsonResponse,
    HttpRequest,
    HttpResponseNotFound,
    HttpResponse,
)
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import permission_required

from .api_documentation import OpenAPIDoc

from .models import (
    DomainFunctionService,
    FunctionService,
    FunctionServiceExecution,
    CustomerFunctionToken,
    FunctionServiceEnvironmentVariable,
    Customer,
)
from .business import (
    FunctionServiceBusiness,
    FunctionServiceEnvironmentVariableBusiness,
    FunctionServiceExecutionBusiness,
    DomainFunctionServiceBusiness,
    CustomerBusiness,
    CustomerFunctionBusiness,
)
from .forms import (
    FunctionServiceForm,
    FunctionServiceEnvironmentVariableForm,
    DomainFunctionServiceForm,
    CustomerForm,
)
from django.forms import model_to_dict

from django.conf import settings
from django.contrib import messages

import json


@csrf_exempt
def execute_function(request, domain, function_url):
    function_service = get_object_or_404(
        FunctionService, url_name=function_url, domain__url_name=domain
    )
    if function_service.http_method not in request.method:
        return HttpResponseNotFound()

    execute_function = False
    customer = None
    if function_service.public:
        execute_function = True
    else:
        cft = CustomerFunctionToken.objects.filter(
            token_id=request.headers.get("Api-Key"), function_service=function_service
        ).first()
        if cft:
            customer = cft.customer
            execute_function = True

    if execute_function:
        environment_variables = FunctionServiceEnvironmentVariable.objects.filter(
            function_service=function_service
        )
        parameters = {"ENV": {}}
        for environment_variable in environment_variables:
            parameters["ENV"][
                environment_variable.name
            ] = environment_variable.load_value
        status_code, response_data = function_service.execute(
            request, customer, **parameters
        )
        return JsonResponse(response_data, status=status_code)
    else:
        return JsonResponse({"error": "invalid token"}, status=403)


def get_openapi_function(
    request: HttpRequest, domain: DomainFunctionService, function_url: str
) -> HttpResponse:
    function_service = get_object_or_404(
        FunctionService, url_name=function_url, domain__url_name=domain
    )
    openapi_schema = OpenAPIDoc.get_openapi_schema_by_function_service(function_service)
    return JsonResponse(json.loads(openapi_schema), json_dumps_params={"indent": 2})


def get_openapi_function_by_domain(request, domain_url_name):
    domain = get_object_or_404(
        DomainFunctionService,
        url_name=domain_url_name,
    )
    openapi_schema = OpenAPIDoc.get_openapi_schema_by_domain_function_service(domain)
    return JsonResponse(json.loads(openapi_schema), json_dumps_params={"indent": 2})


def get_openapi_function_by_team(request, team_name):
    team = get_object_or_404(
        Team,
        slash_name=team_name,
    )
    openapi_schema = OpenAPIDoc.get_openapi_schema_by_team(team)
    return JsonResponse(json.loads(openapi_schema), json_dumps_params={"indent": 2})


@method_decorator(permission_required(settings.API_VIEWER), name="get")
class FunctionListView(ListView):
    template_name = "function/function-list.html"
    paginate_by = 10
    model = FunctionService
    business_class = FunctionServiceBusiness

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.business = self.business_class.factory()

    def get_queryset(self):
        return self.business.get_query_set(
            params=self.request.GET, user=self.request.user
        )


@method_decorator(permission_required(settings.API_VIEWER), name="get")
class FunctionExecutionListView(ListView):
    template_name = "function/function-execution-list.html"
    paginate_by = 10
    model = FunctionServiceExecution
    business_class = FunctionServiceExecutionBusiness

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.business = self.business_class.factory()

    def get_queryset(self):
        return self.business.get_query_set(
            params=self.request.GET, user=self.request.user
        )


class FunctionView(View):
    business_class = FunctionServiceBusiness

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.business = self.business_class.factory()

    @method_decorator(permission_required(settings.API_DEVELOPER))
    def post(self, request: HttpRequest, function_id: int = 0) -> HttpResponse:
        request_data = request.POST.copy()
        if function_id:
            function = self.business.get(function_id=function_id, user=request.user)
            request_data.update({"team": function.team})
        form = FunctionServiceForm(request.user, request_data)
        if form.is_valid():
            object_function = self.business.update_or_create(
                function_id=function_id, params=form.cleaned_data, user=request.user
            )
            messages.success(request, settings.FORM_SAVE_MESSAGE_SUCCESS)
            return redirect(reverse("api_engine:function", args=(object_function.id,)))

    @method_decorator(permission_required(settings.API_VIEWER))
    def get(self, request: HttpRequest, function_id: int = None) -> HttpResponse:
        if function_id:
            function = self.business.get(function_id=function_id, user=request.user)
            form = FunctionServiceForm(
                initial=model_to_dict(function), user=request.user
            )
            environment_variable = FunctionServiceEnvironmentVariable.objects.filter(
                function_service=function
            )
            customer_function = CustomerFunctionToken.objects.filter(
                function_service=function
            )
            customers = Customer.objects.filter(team=function.team).order_by("name")
            executions = FunctionServiceExecution.objects.filter(
                function_service=function
            ).order_by("-created_dt")[0:20]
            extra = {"script": function.code}
            extra["function"] = function
            extra["environment_variable"] = environment_variable
            extra["customer_function"] = customer_function
            extra["customers"] = customers
            extra["executions"] = executions

        else:
            extra = {}
            form = FunctionServiceForm(user=request.user)
        return render(
            request,
            "function/function.html",
            {"form": form, "extra": extra},
        )


class FunctionExecutionView(View):
    business_class = FunctionServiceExecutionBusiness

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.business = self.business_class.factory()

    @method_decorator(permission_required(settings.API_VIEWER))
    def get(self, request: HttpRequest, execution_id: int) -> HttpResponse:
        function_service_execution = self.business.get(
            execution_id=execution_id, user=request.user
        )
        return render(
            request,
            "function/function-execution.html",
            {
                "function_execution": function_service_execution,
            },
        )


class EnvironmentVariableView(View):
    business_class = FunctionServiceEnvironmentVariableBusiness

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.business = self.business_class.factory()

    @method_decorator(permission_required(settings.API_DEVELOPER))
    def post(self, request, function_id):
        form = FunctionServiceEnvironmentVariableForm(request.POST)
        if form.is_valid():
            self.business.update_or_create(
                function_id=function_id,
                params=form.cleaned_data,
                pk=request.POST.get("environment_id", 0),
            )
            messages.success(request, settings.FORM_SAVE_MESSAGE_SUCCESS)
            return redirect(reverse("api_engine:function", args=(function_id,)))

    @method_decorator(permission_required(settings.API_VIEWER))
    def get(self, request, function_id):
        if request.GET.get("method", "").upper() == "DELETE":
            return self.delete(request, function_id)
        return HttpResponseNotFound()

    @method_decorator(permission_required(settings.API_DEVELOPER))
    def delete(self, request, function_id):
        self.business.delete(environment_id=request.GET.get("environment_id"))
        return redirect(reverse("api_engine:function", args=(function_id,)))


class DomainView(View):
    business_class = DomainFunctionServiceBusiness

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.business = self.business_class.factory()

    @method_decorator(permission_required(settings.API_DEVELOPER))
    def post(self, request: HttpRequest, domain_id: int = 0) -> HttpResponse:
        request_data = request.POST.copy()
        if domain_id:
            schedule = self.business.get(domain_id=domain_id, user=request.user)
            request_data.update({"team": schedule.team})
        form = DomainFunctionServiceForm(request.user, request_data)

        if form.is_valid():
            object_domain = self.business.update_or_create(
                domain_id=domain_id, params=form.cleaned_data, user=request.user
            )
            messages.success(request, settings.FORM_SAVE_MESSAGE_SUCCESS)
            return redirect(reverse("api_engine:domain", args=(object_domain.id,)))

app/api_engine/templates/customer/customer-list.html
{% extends "model-page.html"%}
{% block content %}
{% load i18n %}
{% load static %}
{% load list_extras %}
{% load execution_extras %}



<div class="page-title">
    <h3>{% translate "Parceiros" %}</h3>
</div>
<section class="section">

    <div class="card">
        <div class="card-header">
            Lista de Parceiros
        </div>
        <div class="card-body">
            <form>
                <div class="form-group mb-1">
                    <input class="form-control" type="text" name="name" placeholder="Buscar por nome...">            
                </div>
                <button type="submit" class="btn btn-primary">Buscar</button>
            <form>

            <table class="table table-striped mt-4 table-responsive-md">
                <thead>
                    <tr>
                        <th>
                            <a class="text-green" href="{% order_by_href "name" request.GET.order_by request.GET.name %}">
                            {% order_by "name" request.GET.order_by as arrow_name %}
                            {{ arrow_name | safe}}
                            Nome 
                            </a>
                        </th>
                        <th>
                            <a class="text-green"  href="{% order_by_href "team__name" request.GET.order_by %}">
                            {% order_by "team__name" request.GET.order_by as arrow_team %}
                            {{ arrow_team | safe}}
                            Time
                            </a>
                        </th>
                        <th>
                            <a class="text-green"  href="{% order_by_href "created_date" request.GET.order_by request.GET.name %}">
                            {% order_by "created_date" request.GET.order_by as arrow_created_date %}
                            {{ arrow_created_date | safe}}
                            Data de Criação
                            </a>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for customer in object_list %}
                        <tr>
                            <td>{{ customer.get_html_hyperlink|safe }}</a></td>
                            <td>{{ customer.team.name }}</td>
                            <td>{{ customer.created_date }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>            
            {% include "pagination.html" %}
        </div>
    </div>
</section>

{% endblock %}

app/api_engine/templates/customer/customer.html
{% extends "model-page.html"%}
{% block content %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

<div class="page-title">
    <h3>{% translate "Parceiro" %}</h3>
</div>
<section class="section">
    <div class="card">
        {% comment %} <div class="card-header">
            Domínio
        </div> {% endcomment %}


        <div class="card-body">
            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                <div class="card-body">
                    {% if form.erros %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                    {% endif %}

                    {% if messages %}
                        <div class="row">
                            <ul class="messages">
                                {% for message in messages %}
                                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                                        <strong>{{ message }}</strong>
                                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                    </div>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    
                    <form action=
                            {% if extra.customer%}
                                {% url 'api_engine:customer' extra.customer.id %}
                            {% else %}
                                {% url 'api_engine:customer' %}
                            {% endif %}
                            method='POST'>{% csrf_token %}
                
                        {{ form.name|as_crispy_field }}
                        <div class="row">
                            <div class="form-group col">
                                {{ form.team|as_crispy_field }}
                            </div>   

                        </div>            
                        {% if perms.api_engine.change_api %}                  
                        <button type="submit" class="btn btn-success">{% trans 'Save' %}</button>
                        {% endif %}
                    </form>
                
                </div>
            </div>                
        </div>
    </div>
</section>

<script>
    let python_editor = document.getElementsByClassName("python-editor");
    
    Array.prototype.forEach.call(python_editor, function(el) {
        var editor = CodeMirror.fromTextArea(el, {
            lineNumbers: true,
            gutters: ["CodeMirror-linenumbers", "breakpoints"],
            styleActiveLine: true,
            matchBrackets: true,
            theme: "default",
            mode: "python",
        });
        editor.save()
    });
    $(".alert-success").fadeTo(2000, 500).slideUp(500, function(){});
</script>

{% endblock %}